### ISSUE TITLE
[feat]주문서 Order

### ISSUE THREAD

**Issue by Hyeromon** [prgrms-be-devcourse/NBE2-3-2-team10#12]
### ✅ To-do

- [x] 고객 정보 조회 (이름,주소)
- [x] 세탁소 정보 조회(이름)
- [x] 주문서 작성(개수, 요청사항)
- [x] 카테고리 부분 생성 및 추가하기
- [x] 주문서 조회
- [x] 주문서 조회 (상세보기)
- [x] 주문서 조회 클릭시 상세보기 페이지로 이동하는 기능 추가하기
- [x] 취소버튼 클릭시 status -> CANCELLED로 변경
