### ISSUE TITLE
[Feat] Pickup "Status:픽업 완료" 를 주문 내역을 페이지에서 조회 후 "작업 완료"로 변경 시키는 기능 개발

### ISSUE THREAD

**Issue by moon-kun-woong** [prgrms-be-devcourse/NBE2-3-2-team10#22]
### 💼 작업 설명
footer 의 '주문내역' 버튼 클릭 시 pickupList 페이지에서 PICKUPED 상태의 pickup 조회. 상세 보기 클릭 시 "작업 완료" 변경.

### ✅ To-do
- [x] PICKED_UP 상태의 pickup 요청을 조회해 PICKED_UP 상태를 PAYMENT_PENDING(결제 대기) 상태로 업데이트.
- [x] pickup-list 페이지에 PAYMENT_PENDING(결제 대기) 와 IN_PROGRESS(작업중) 상태의 pickup 을 표시. 상세 내역 누를 시, 해당 pickup_id attribute 를 들고 pickup-detail로 이동
- [x] pickup-detail 페이지에 pickup_id 로 조회 된 pickup 요청을 표시하고 "결제 대기 중" 상태일 경우와 "작업 중" 상태일 경우 각각 버튼이 "뒤로 가기" , "작업 완료, 뒤로 가기" 로 각각 나누어 표시.
- [x] "작업 완료" 버튼을 누를 시, 뒤로 가기 버튼만 남기고 새로고침 한다. 이때 요청 중 24시가 지난 요청이라면 NONE 상태가 되어서 어디에서도 조회 되지 않도록 구현
