### ISSUE TITLE
[Feat] 세탁소 상세정보 조회 기능 개발

### ISSUE THREAD

**Issue by niki8533** [prgrms-be-devcourse/NBE2-3-2-team10#34]
### 💼 작업 설명

세탁소 상세 정보 조회
### ✅ To-do

- [x] 세탁소 id 넘기고 받는거 확인
- [x] 세탁소 id랑 일치하는 데이터 찾아서 출력하기
- [x] 카테고리
- [x] 세탁 신청 버튼 연결
