### ISSUE TITLE
[feat] sales-summary 기능 개발

### ISSUE THREAD

**Issue by moon-kun-woong** [prgrms-be-devcourse/NBE2-3-2-team10#45]
### 💼 작업 설명
DELIVERED("도착 완료") 상태인 pickup 의 totalPrice 의 값을 합산해 표로 보여주는 기능 구현.

### ✅ To-do
- [x] sales-summary page 에서 현 년도 -2년 까지의 (예: 현재 2024 라면 2024, 2023, 2022 까지) 달에 맞는 날짜로 위치 시킨다.
- [x] 위치 시킨 달의 날짜에 해당하는 pickup 의 laundryShopName 와 totalPrice 를 리스트에 맞게 반환하고 최신 순으로 정렬.
- [x] 그 달의 totalPrice 전체 금액을 보여주도록 "총 매출액" 을 표시.
