### ISSUE TITLE
[Fix] 세탁소 정보 저장 및 수정 기능 수정

### ISSUE THREAD

**Issue by niki8533** [prgrms-be-devcourse/NBE2-3-2-team10#56]
### 💼 작업 설명

세탁소 정보 저장 및 수정 기능 수정
### ✅ To-do

- [x] 마이 페이지 버튼 연결
- [x] 정보 저장/수정되면 home으로 리다이렉트
- [x] shop-my-page에서 저장/수정 페이지 연결
- [x] 정보 저장 시 에러 발생 안하게 수정
