### ISSUE TITLE
[Feat] 일반 회원 가입 기능 개발

### ISSUE THREAD

**Issue by LeeVell** [prgrms-be-devcourse/NBE2-3-2-team10#8]
### 💼 작업 설명
유저의 회원가입 기능 개발
( 이메일, 패스워드, 이름, 주소, 휴대폰번호, 권한 )

### ✅ To-do

- [x] RequestBody를 받아 검증 후 DB에 회원 데이터 추가

- [x] JWT 인증 인가는 추후 추가
- [x] 일반 회원가입 시 kakao_id(NULL) 넣도록 추가
