### ISSUE TITLE
[Feat] 세탁소 정보 등록 기능 개발

### ISSUE THREAD

**Issue by niki8533** [prgrms-be-devcourse/NBE2-3-2-team10#9]
### 💼 작업 설명
세탁소 정보 등록 기능 개발
feat/laundry/4

### ✅ To-do
- [x] 세탁소 폼 입력 내용 받아 DB에 저장
- [x] response.ok 넘기기
- [x] user_id 값 넘기기 -> 추후 수정 필요
- [x] 가격표 행 추가, 삭제 버튼 생성
- [x] 가격표 저장하기
- [x] laundry_id랑 연결해서 저장하기
- [x] 세탁소 정보가 이미 있으면 데이터 불러오기
- [x] 세탁소 정보 수정인지 등록인지 구분해서 데이터 저장하기
- [x] 가격 바뀌면 바뀐 가격으로 저장하기
- [x] 데이터 삭제하면 삭제 반영하기
